//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Page.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AfiliacionMB
    {
        public int cedula { get; set; }
        public Nullable<long> CodigoCuenta { get; set; }
        public int TelefonAfi { get; set; }
        public Nullable<decimal> MontoTran { get; set; }
        public string nickname { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual Cuenta Cuenta { get; set; }
    }
}
