//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Page.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuenta()
        {
            this.AfiliacionMBs = new HashSet<AfiliacionMB>();
            this.Tranferencias = new HashSet<Tranferencia>();
            this.TranferenciasWebs = new HashSet<TranferenciasWeb>();
            this.TranferenciasSMS = new HashSet<TranferenciasSM>();
        }
    
        public long CodigCuenta { get; set; }
        public Nullable<int> TipoCuenta { get; set; }
        public Nullable<int> Cedula { get; set; }
        public Nullable<decimal> Monto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AfiliacionMB> AfiliacionMBs { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual TiposCuenta TiposCuenta { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tranferencia> Tranferencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TranferenciasWeb> TranferenciasWebs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TranferenciasSM> TranferenciasSMS { get; set; }
    }
}
