//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Page.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tranferencia
    {
        public int CodTranf { get; set; }
        public Nullable<long> CodCuenta { get; set; }
        public string Tipocuenta { get; set; }
        public Nullable<decimal> MontoR { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
    }
}
